# Generated by Django 3.2.7 on 2021-09-24 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('task_name', models.TextField(max_length=500, verbose_name='タスク名')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('question_text', models.TextField(max_length=500, verbose_name='質問')),
                ('hashtag', models.CharField(max_length=100, verbose_name='ハッシュタグ')),
                ('aggregate_start_time', models.DateTimeField(default=None, null=True, verbose_name='集計開始時間')),
                ('aggregate_end_time', models.DateTimeField(default=None, null=True, verbose_name='集計終了')),
            ],
            options={
                'verbose_name': '自由記述式アンケート',
                'verbose_name_plural': '自由記述式アンケート',
            },
        ),
    ]
