# Generated by Django 3.2.7 on 2021-09-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_answer', '0002_remove_question_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='result_json',
            field=models.TextField(default='', verbose_name='結果JSON'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='aggregate_end_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='集計終了'),
        ),
        migrations.AlterField(
            model_name='question',
            name='aggregate_start_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='集計開始時間'),
        ),
    ]
